name: Steam Release Bug Report
description: File a bug report related to the Steam release version of Pre-Fortress 2.
title: "[Steam Release][Bug]: "
labels: ["bug", "steam release"]
type: bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: operarting-system
    attributes:
      label: Operating System
      description: What operating sytem are you on?
      options:
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: distro
    attributes:
      label: (LINUX ONLY) What distro are you using? 
      placeholder: (e.g. Linux Mint 22.2, CachyOS Desktop 260308)
    validations:
      required: false

  - type: input
    id: proton
    attributes:
      label: (LINUX ONLY) What version of Proton are you using? 
      placeholder: (e.g. Proton Experimental, GE-Proton10-32)
    validations:
      required: false

  - type: textarea
    id: pc-specs
    attributes:
      label: What are your computer specs?
      placeholder: |
        GPU: RTX2070 Super
        CPU: AMD Ryzon 7800X3D
        RAM: 32GB DDR5
        Storage: 1TB NVMe SSD
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug.
      description: A clear and concise description of what the bug is. When reporting a bug it helpfuls to list out the steps it took to encounter the bug.
      placeholder: There was a [problem] when doing [action] while on [map name] and playing [class].
    validations:
      required: true

  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: checkboxes
    id: agreement
    attributes:
      label: Agreements
      options:
        - label: I confirm I have tested this issue without mods and confirm it still occurs.
          required: true
        - label: I have searched existing issues and confirm this issue is new.
          required: true

